### A Pluto.jl notebook ###
# v0.18.4

using Markdown
using InteractiveUtils

# ╔═╡ f06d10ba-8ece-488d-a713-5595dbd5afc4
using Primes

# ╔═╡ 94c29000-b114-11ec-3464-034d52d2eefe
include("$(@__DIR__)/Check.jl")

# ╔═╡ 68c8db34-1ff3-472c-98c2-23355a61525f
#=
   The sequence of triangle numbers is generated by adding the natural
   numbers. So the 7^th triangle number would be 1 + 2 + 3 + 4 + 5 + 6 + 7 =
   28. The first ten terms would be:

                    1, 3, 6, 10, 15, 21, 28, 36, 45, 55, ...

   Let us list the factors of the first seven triangle numbers:

      1: 1
      3: 1,3
      6: 1,2,3,6
     10: 1,2,5,10
     15: 1,3,5,15
     21: 1,3,7,21
     28: 1,2,4,7,14,28
=#

# ╔═╡ c0be1335-b537-493f-abf9-138541df589d
function divisors(n)
    d = Int64[1]
    for (p,e) in factor(n)
        t = Int64[]
        r = 1
        for i in 1:e
            r *= p
            for u in d
                push!(t, u*r)
            end
        end
        append!(d, t)
    end
    return length(d)
end

# ╔═╡ d5f6b78a-8c72-415f-8f2b-f49b696541f9
function triang()
	c = 0
	for i in 1:99999999999
		c += i
		if divisors(c) >500
			return c
		end
	end
end

# ╔═╡ 4553faab-ef72-40cc-8153-7052fb0e34e0
resposta = triang()

# ╔═╡ b6aa8488-dc44-46a0-b798-a2a166bd7884
Check(12, resposta)

# ╔═╡ 00000000-0000-0000-0000-000000000001
PLUTO_PROJECT_TOML_CONTENTS = """
[deps]
Primes = "27ebfcd6-29c5-5fa9-bf4b-fb8fc14df3ae"

[compat]
Primes = "~0.5.2"
"""

# ╔═╡ 00000000-0000-0000-0000-000000000002
PLUTO_MANIFEST_TOML_CONTENTS = """
# This file is machine-generated - editing it directly is not advised

julia_version = "1.7.2"
manifest_format = "2.0"

[[deps.IntegerMathUtils]]
git-tree-sha1 = "f366daebdfb079fd1fe4e3d560f99a0c892e15bc"
uuid = "18e54dd8-cb9d-406c-a71d-865a43cbb235"
version = "0.1.0"

[[deps.Primes]]
deps = ["IntegerMathUtils"]
git-tree-sha1 = "747f4261ebe38a2bc6abf0850ea8c6d9027ccd07"
uuid = "27ebfcd6-29c5-5fa9-bf4b-fb8fc14df3ae"
version = "0.5.2"
"""

# ╔═╡ Cell order:
# ╠═94c29000-b114-11ec-3464-034d52d2eefe
# ╠═68c8db34-1ff3-472c-98c2-23355a61525f
# ╠═f06d10ba-8ece-488d-a713-5595dbd5afc4
# ╠═b6aa8488-dc44-46a0-b798-a2a166bd7884
# ╠═c0be1335-b537-493f-abf9-138541df589d
# ╠═d5f6b78a-8c72-415f-8f2b-f49b696541f9
# ╠═4553faab-ef72-40cc-8153-7052fb0e34e0
# ╟─00000000-0000-0000-0000-000000000001
# ╟─00000000-0000-0000-0000-000000000002
