### A Pluto.jl notebook ###
# v0.18.4

using Markdown
using InteractiveUtils

# ╔═╡ 7a4c2624-a92a-11ec-2a9f-672d78fb5022
include("/home/lorenzovaralo/Documentos/ProjetosPython/Project_Euler/Check.jl")

# ╔═╡ 63ecf787-694e-4f91-bdaf-63680e39f45e
#=
Each new term in the Fibonacci sequence is generated by adding the
   previous two terms. By starting with 1 and 2, the first 10 terms will be:

                     1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

   By considering the terms in the Fibonacci sequence whose values do not
   exceed four million, find the sum of the even-valued terms.
=#

# ╔═╡ db8d0af2-fcd3-4a06-b75d-81771a08d69f
ϕ = abs(0.5 + im)+0.5

# ╔═╡ 69d7f499-0656-4caf-b335-0d99b00fadf8
a=2

# ╔═╡ 87bcbb58-9e57-4928-b60c-9050137119fe
resposta = BigInt(sum([a = round(ϕ^3 * a) for b in 1:100 if round(ϕ^3 * a) < 4_000_000]))+2

# ╔═╡ 24b63238-3a62-4afa-9868-3454d7e74289
Check(2, resposta)

# ╔═╡ 00000000-0000-0000-0000-000000000001
PLUTO_PROJECT_TOML_CONTENTS = """
[deps]
"""

# ╔═╡ 00000000-0000-0000-0000-000000000002
PLUTO_MANIFEST_TOML_CONTENTS = """
# This file is machine-generated - editing it directly is not advised

julia_version = "1.7.2"
manifest_format = "2.0"

[deps]
"""

# ╔═╡ Cell order:
# ╠═7a4c2624-a92a-11ec-2a9f-672d78fb5022
# ╠═63ecf787-694e-4f91-bdaf-63680e39f45e
# ╠═24b63238-3a62-4afa-9868-3454d7e74289
# ╠═db8d0af2-fcd3-4a06-b75d-81771a08d69f
# ╠═69d7f499-0656-4caf-b335-0d99b00fadf8
# ╠═87bcbb58-9e57-4928-b60c-9050137119fe
# ╟─00000000-0000-0000-0000-000000000001
# ╟─00000000-0000-0000-0000-000000000002
